### PR TITLE
[HYRAX-1732] Add AWS signing

### PR DESCRIPTION
**Pull request by hannahilea**
## Description

Intermediate branch for pulling in the aws sdk functionality.

### CODE REVIEW

**Comment by hannahilea** [comment]
```  
Undefined symbols for architecture arm64:
"Aws::S3::S3ClientConfiguration::S3ClientConfiguration(Aws::Client::ClientConfigurationInitValues const&)", referenced from:
      bes::AWS_SDK::AWS_SDK() in libbes_http.a[8](SignedUrlCache.o)
  "Aws::S3::S3Client::S3Client(Aws::S3::S3ClientConfiguration const&, std::__1::shared_ptr<Aws::Endpoint::EndpointProviderBase<Aws::S3::S3ClientConfiguration, Aws::S3::Endpoint::S3BuiltInParameters, Aws::S3::Endpoint::S3ClientContextParameters>>)", referenced from:
      bes::AWS_SDK::AWS_SDK() in libbes_http.a[8](SignedUrlCache.o)
  "Aws::S3::S3Client::~S3Client()", referenced from:
      bes::AWS_SDK::~AWS_SDK() in libbes_http.a[8](SignedUrlCache.o)
  "Aws::Free(void*)", referenced from:
      void Aws::DeleteArray<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*) in libbes_http.a[8](SignedUrlCache.o)
  "vtable for bes::AWS_SDK", referenced from:
      bes::AWS_SDK::AWS_SDK() in libbes_http.a[8](SignedUrlCache.o)
      bes::AWS_SDK::~AWS_SDK() in libbes_http.a[8](SignedUrlCache.o)
   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [build_dmrpp_h4] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
😢

**Comment by hannahilea** [comment]
okay, this branch works in isolation---i'm merging it into #1183, where it can be reviewed in the future.
